name: Awesome Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run awesome-lint
        run: npx --yes awesome-lint
